'use strict';

module.exports = {
  COMPILE_GRAMMAR: 'COMPILE_GRAMMAR',
  GRAMMAR_COMPILED: 'GRAMMAR_COMPILED',
  GRAMMAR_ERRORED: 'GRAMMAR_ERRORED',
  PARSE_TEXT: 'PARSE_TEXT',
  TEXT_PARSED: 'TEXT_PARSED',
  TEXT_ERRORED: 'TEXT_ERRORED',
  TEXT_TO_PARSE_CHANGED: 'TEXT_TO_PARSE_CHANGED',
  GRAMMAR_CHANGED: 'GRAMMAR_CHANGED',
  GRAMMAR_CHANGED_SIGNIFICANTLY: 'GRAMMAR_CHANGED_SIGNIFICANTLY'
};
