'use strict';

module.exports = {
  COMPILE_GRAMMAR: 'COMPILE_GRAMMAR',
  GRAMMAR_COMPILED: 'GRAMMAR_COMPILED',
  GRAMMAR_ERRORED: 'GRAMMAR_ERRORED',
  PARSE_TEXT: 'PARSE_TEXT',
  TEXT_PARSED: 'TEXT_PARSED',
  TEXT_ERRORED: 'TEXT_ERRORED'
};
