'use strict';

var random = require('lodash/number/random');

// give each token type a relatively unique color
// generated by https://github.com/sterlingwes/RandomColor
var colors = [
  "rgb(97, 179, 60)",
  "rgb(179, 60, 132)",
  "rgb(60, 166, 179)",
  "rgb(179, 157, 60)",
  "rgb(122, 60, 179)",
  "rgb(60, 179, 88)",
  "rgb(179, 60, 68)",
  "rgb(60, 102, 179)",
  "rgb(137, 179, 60)",
  "rgb(179, 60, 171)",
  "rgb(60, 179, 152)",
  "rgb(179, 117, 60)",
  "rgb(83, 60, 179)",
  "rgb(73, 179, 60)",
  "rgb(179, 60, 107)",
  "rgb(60, 142, 179)",
  "rgb(176, 179, 60)",
  "rgb(147, 60, 179)",
  "rgb(60, 179, 112)",
  "rgb(179, 78, 60)",
  "rgb(60, 78, 179)",
  "rgb(112, 179, 60)",
  "rgb(179, 60, 147)",
  "rgb(60, 179, 176)",
  "rgb(179, 142, 60)",
  "rgb(107, 60, 179)"
];
// shuffled because it's more fun
var colorIdx = random(0, colors.length - 1);
var tokenNamesToColors = {};

function getColorFor(tokenName) {
  if (!tokenNamesToColors[tokenName]) {
    tokenNamesToColors[tokenName] = colors[colorIdx];
    colorIdx++;
    if (colorIdx == colors.length) {
      colorIdx = 0; // wrap back around
    }
  }

  return tokenNamesToColors[tokenName];
}

module.exports = {
  getColorFor: getColorFor
};
